version: "{build}"

platform: x64

branches:
  only:
    - development

clone_folder: c:\gopath\src\github.com\ubis\Freya

environment:
  GOPATH: c:\gopath\src\github.com\ubis\Freya

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v loginserver
  - go get -v gameserver
  - go get -v masterserver
  - go install -v loginserver
  - go install -v gameserver
  - go install -v masterserver

build: false
deploy: false
